### ISSUE TITLE
Installation instructions in readme incomplete?

### ISSUE THREAD

**Issue by sdbbs** [JuanmaMenendez/website-change-monitor#2]
The current version of README.md says:

> ## Installation
>
> 1. Clone this repo `git clone https://github.com/JuanmaMenendez/website-change-monitor.git`
>
> 2. `npm install`

Since I don't work with `npm` regularly, this got me a bit confused - but eventually, I found that `npm install` needs to refer to a `package.json` file in the command calling directory.

So, shouldn't the instructions be like this?:

1. Clone this repo `git clone https://github.com/JuanmaMenendez/website-change-monitor.git`
2. Change directory `cd website-change-monitor`
3, Run `npm install`

**Comment by JuanmaMenendez** [comment]
You are right @sdbbs but as `npm `is very popular these days most developers know that `npm install` is related to _package.json_, for that reason I was not very specific in that steps. Anyway thanks for your comment, it is valid.
