### ISSUE TITLE
how to check for specific element changed

### ISSUE THREAD

**Issue by bkrajendra** [JuanmaMenendez/website-change-monitor#8]
I have a webpage with list of codes, and I want to check if new code is added in the `<ol>` li element
How should I put ```const elementsToSearchFor = ['<ol>'];``` or ```const elementsToSearchFor = ['<li>'];```

or any other way to monitor the content of these `<ol>` tags.
also, what happens if I have more than one `<ol>` tag?

**Comment by JuanmaMenendez** [comment]
In that case, I recommend you replace the code of  "body.includes(el)" by something like https://www.npmjs.com/package/cheerio selectors.

**Comment by JuanmaMenendez** [comment]
Was just a question for a specific case.
